#!/bin/bash

#############
# Author: Amrapali Tirpude
# Date: 11/11/2023
# Version: v1 
# This script will report the AWS resource usage
# 
#############

# to put in debug mode
set -x

# AWS EC2
# AWS S3
# AWS Lambda
# AWS IAM users

# list ec2 instances
echo "Print list of EC2 instances"
aws ec2 describe-instances | jq '.Reservations[].Instances[].InstanceId'


# list S3 buckets
echo "Print list of S3 bucket"
aws s3 ls


# list lambda
echo "Print list of lambda functions"
aws lambda list-functions


# list IAM users
echo "Print list of IAM users"
aws iam list-users
